apiVersion: mesh.webmesh.io/v1
kind: NodeGroup
metadata:
  name: cluster-nodegroup
spec:
  replicas: 1
  cluster:
    imagePullPolicy: Always
  config:
    logLevel: debug
  mesh:
    name: mesh-sample
