apiVersion: mesh.webmesh.io/v1
kind: Mesh
metadata:
  name: mesh-sample
spec:
  issuer:
    create: true
  bootstrap:
    replicas: 3
    cluster:
      imagePullPolicy: Always
      service:
        type: LoadBalancer
    config:
      logLevel: debug
      services:
        enablePeerDiscoveryAPI: true
        meshDNS: {}
