apiVersion: mesh.webmesh.io/v1
kind: NodeGroup
metadata:
  name: gcloud-nodegroup
  labels:
    webmesh.io/zone-awareness: mesh-sample-bootstrap
spec:
  googleCloud:
    projectID: webmeshproj
    subnetwork: webmesh-external
    zone: us-central1-a
    machineType: e2-standard-2
    tags: ["mesh-nodes"]
  config:
    logLevel: debug
    services:
      enableMeshAPI: true
      enableLeaderProxy: true
  mesh:
    name: mesh-sample
