apiVersion: mesh.webmesh.io/v1
kind: NodeGroup
metadata:
  name: cluster-nodegroup
  labels:
    webmesh.io/zone-awareness: mesh-sample-bootstrap
spec:
  replicas: 1
  cluster:
    imagePullPolicy: Always
  config:
    logLevel: debug
  mesh:
    name: mesh-sample
