name: CI
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]

env:
  IMAGE_NAME: ghcr.io/webmeshproj/operator
  GO_VERSION: ^1.20
  PLATFORMS: linux/amd64,linux/arm64,linux/arm

jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache-dependency-path: go.sum

      - name: Download Go Modules
        shell: bash
        run: go mod download -x

      - name: Run linting
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53.2
          args: --timeout 10m
          skip-pkg-cache: true

  build-publish:
    name: Build and Publish Artifacts
    runs-on: ubuntu-latest
    needs: [tests]
    permissions:
      contents: "write"
      id-token: "write"
      packages: "write"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache-dependency-path: go.sum

      - name: Download Go Modules
        shell: bash
        run: go mod download -x

      - name: Setup Cosign
        uses: sigstore/cosign-installer@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Cross Compiler Image
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.build
          tags: ghcr.io/webmeshproj/operator-build:latest
          load: true
          cache-to: type=gha
          cache-from: type=gha

      - name: Build Release Binaries
        shell: bash
        env:
          BUILD_IMAGE: ghcr.io/webmeshproj/operator-build:latest
        run: make dist

      - name: Login to GHCR
        uses: docker/login-action@v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Get Image Tags
        shell: bash
        id: tags
        run: |
          IMAGES="${IMAGE_NAME}:latest,${IMAGE_NAME}:${{ github.sha }}"
          if [[ ${{ github.ref_name }} =~ ^v.* ]] ; then
            IMAGES+=",${IMAGE_NAME}:${{ github.ref_name }}"
          fi
          echo "images=${IMAGES}" >> "${GITHUB_OUTPUT}"

      - name: Build and Push Images
        uses: docker/build-push-action@v3
        id: build
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.tags.outputs.images }}
          platforms: ${{ env.PLATFORMS }}
          cache-to: type=gha
          cache-from: type=gha

      - name: Sign Images
        shell: bash
        if: ${{ github.event_name != 'pull_request' }}
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          cosign sign --yes --recursive ${IMAGE_NAME}@${{ steps.build.outputs.digest }}
