name: CI
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]

env:
  IMAGE_NAME: ghcr.io/webmeshproj/operator
  GO_VERSION: ^1.20
  GOLANGCI_LINT_VERSION: v1.53.2
  DOCKER_PLATFORMS: linux/amd64,linux/arm64,linux/arm,linux/ppc64le,linux/s390x

jobs:
  lint:
    name: Static Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache-dependency-path: go.sum

      - name: Download Go Modules
        shell: bash
        run: go mod download -x

      - name: Run Linting
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          args: --timeout 10m
          skip-pkg-cache: true

  tests:
    name: Unit Tests
    needs: [lint]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: "read"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache-dependency-path: go.sum

      - name: Download Go Modules
        shell: bash
        run: go mod download -x

      - name: Run Unit Tests
        shell: bash
        run: make test

  build:
    name: Build and Publish Artifacts
    runs-on: ubuntu-latest
    needs: [tests]
    permissions:
      contents: "write"
      id-token: "write"
      packages: "write"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache-dependency-path: go.sum

      - name: Download Go Modules
        shell: bash
        run: go mod download -x

      - name: Setup Cosign
        uses: sigstore/cosign-installer@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Release Binaries
        shell: bash
        run: make dist DIST_PARALLEL=2

      - name: Login to GHCR
        uses: docker/login-action@v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Get Image Tags
        shell: bash
        id: tags
        run: |
          IMAGES="${IMAGE_NAME}:latest,${IMAGE_NAME}:${{ github.sha }}"
          if [[ ${{ github.ref_name }} =~ ^v.* ]] ; then
            IMAGES+=",${IMAGE_NAME}:${{ github.ref_name }}"
          fi
          echo "images=${IMAGES}" >> "${GITHUB_OUTPUT}"

      - name: Build and Push Images
        uses: docker/build-push-action@v4
        id: build
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.tags.outputs.images }}
          platforms: ${{ env.DOCKER_PLATFORMS }}

      - name: Sign Images
        shell: bash
        if: ${{ github.event_name != 'pull_request' }}
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          cosign sign --yes --recursive ${IMAGE_NAME}@${{ steps.build.outputs.digest }}
